<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paises = [
            ['nome' => 'Afghanistan', 'codigo' => 'AF'],
            ['nome' => 'Albania', 'codigo' => 'AL'],
            ['nome' => 'Algeria', 'codigo' => 'DZ'],
            ['nome' => 'American Samoa', 'codigo' => 'AS'],
            ['nome' => 'Andorra', 'codigo' => 'AD'],
            ['nome' => 'Angola', 'codigo' => 'AO'],
            ['nome' => 'Anguilla', 'codigo' => 'AI'],
            ['nome' => 'Antarctica', 'codigo' => 'AQ'],
            ['nome' => 'Antigua and Barbuda', 'codigo' => 'AG'],
            ['nome' => 'Argentina', 'codigo' => 'AR'],
            ['nome' => 'Armenia', 'codigo' => 'AM'],
            ['nome' => 'Aruba', 'codigo' => 'AW'],
            ['nome' => 'Australia', 'codigo' => 'AU'],
            ['nome' => 'Austria', 'codigo' => 'AT'],
            ['nome' => 'Azerbaijan', 'codigo' => 'AZ'],
            ['nome' => 'Bahamas', 'codigo' => 'BS'],
            ['nome' => 'Bahrain', 'codigo' => 'BH'],
            ['nome' => 'Bangladesh', 'codigo' => 'BD'],
            ['nome' => 'Barbados', 'codigo' => 'BB'],
            ['nome' => 'Belarus', 'codigo' => 'BY'],
            ['nome' => 'Belgium', 'codigo' => 'BE'],
            ['nome' => 'Belize', 'codigo' => 'BZ'],
            ['nome' => 'Benin', 'codigo' => 'BJ'],
            ['nome' => 'Bermuda', 'codigo' => 'BM'],
            ['nome' => 'Bhutan', 'codigo' => 'BT'],
            ['nome' => 'Bolivia', 'codigo' => 'BO'],
            ['nome' => 'Bosnia and Herzegovina', 'codigo' => 'BA'],
            ['nome' => 'Botswana', 'codigo' => 'BW'],
            ['nome' => 'Brazil', 'codigo' => 'BR'],
            ['nome' => 'Brunei', 'codigo' => 'BN'],
            ['nome' => 'Bulgaria', 'codigo' => 'BG'],
            ['nome' => 'Burkina Faso', 'codigo' => 'BF'],
            ['nome' => 'Burundi', 'codigo' => 'BI'],
            ['nome' => 'Cabo Verde', 'codigo' => 'CV'],
            ['nome' => 'Cambodia', 'codigo' => 'KH'],
            ['nome' => 'Cameroon', 'codigo' => 'CM'],
            ['nome' => 'Canada', 'codigo' => 'CA'],
            ['nome' => 'Central African Republic', 'codigo' => 'CF'],
            ['nome' => 'Chad', 'codigo' => 'TD'],
            ['nome' => 'Chile', 'codigo' => 'CL'],
            ['nome' => 'China', 'codigo' => 'CN'],
            ['nome' => 'Colombia', 'codigo' => 'CO'],
            ['nome' => 'Comoros', 'codigo' => 'KM'],
            ['nome' => 'Congo', 'codigo' => 'CG'],
            ['nome' => 'Congo (DRC)', 'codigo' => 'CD'],
            ['nome' => 'Costa Rica', 'codigo' => 'CR'],
            ['nome' => 'Croatia', 'codigo' => 'HR'],
            ['nome' => 'Cuba', 'codigo' => 'CU'],
            ['nome' => 'Cyprus', 'codigo' => 'CY'],
            ['nome' => 'Czechia', 'codigo' => 'CZ'],
            ['nome' => 'Denmark', 'codigo' => 'DK'],
            ['nome' => 'Djibouti', 'codigo' => 'DJ'],
            ['nome' => 'Dominica', 'codigo' => 'DM'],
            ['nome' => 'Dominican Republic', 'codigo' => 'DO'],
            ['nome' => 'Ecuador', 'codigo' => 'EC'],
            ['nome' => 'Egypt', 'codigo' => 'EG'],
            ['nome' => 'El Salvador', 'codigo' => 'SV'],
            ['nome' => 'Equatorial Guinea', 'codigo' => 'GQ'],
            ['nome' => 'Eritrea', 'codigo' => 'ER'],
            ['nome' => 'Estonia', 'codigo' => 'EE'],
            ['nome' => 'Eswatini', 'codigo' => 'SZ'],
            ['nome' => 'Ethiopia', 'codigo' => 'ET'],
            ['nome' => 'Fiji', 'codigo' => 'FJ'],
            ['nome' => 'Finland', 'codigo' => 'FI'],
            ['nome' => 'France', 'codigo' => 'FR'],
            ['nome' => 'Gabon', 'codigo' => 'GA'],
            ['nome' => 'Gambia', 'codigo' => 'GM'],
            ['nome' => 'Georgia', 'codigo' => 'GE'],
            ['nome' => 'Germany', 'codigo' => 'DE'],
            ['nome' => 'Ghana', 'codigo' => 'GH'],
            ['nome' => 'Greece', 'codigo' => 'GR'],
            ['nome' => 'Grenada', 'codigo' => 'GD'],
            ['nome' => 'Guatemala', 'codigo' => 'GT'],
            ['nome' => 'Guinea', 'codigo' => 'GN'],
            ['nome' => 'Guinea-Bissau', 'codigo' => 'GW'],
            ['nome' => 'Guyana', 'codigo' => 'GY'],
            ['nome' => 'Haiti', 'codigo' => 'HT'],
            ['nome' => 'Honduras', 'codigo' => 'HN'],
            ['nome' => 'Hungary', 'codigo' => 'HU'],
            ['nome' => 'Iceland', 'codigo' => 'IS'],
            ['nome' => 'India', 'codigo' => 'IN'],
            ['nome' => 'Indonesia', 'codigo' => 'ID'],
            ['nome' => 'Iran', 'codigo' => 'IR'],
            ['nome' => 'Iraq', 'codigo' => 'IQ'],
            ['nome' => 'Ireland', 'codigo' => 'IE'],
            ['nome' => 'Israel', 'codigo' => 'IL'],
            ['nome' => 'Italy', 'codigo' => 'IT'],
            ['nome' => 'Jamaica', 'codigo' => 'JM'],
            ['nome' => 'Japan', 'codigo' => 'JP'],
            ['nome' => 'Jordan', 'codigo' => 'JO'],
            ['nome' => 'Kazakhstan', 'codigo' => 'KZ'],
            ['nome' => 'Kenya', 'codigo' => 'KE'],
            ['nome' => 'Kuwait', 'codigo' => 'KW'],
            ['nome' => 'Kyrgyzstan', 'codigo' => 'KG'],
            ['nome' => 'Laos', 'codigo' => 'LA'],
            ['nome' => 'Latvia', 'codigo' => 'LV'],
            ['nome' => 'Lebanon', 'codigo' => 'LB'],
            ['nome' => 'Lesotho', 'codigo' => 'LS'],
            ['nome' => 'Liberia', 'codigo' => 'LR'],
            ['nome' => 'Libya', 'codigo' => 'LY'],
            ['nome' => 'Liechtenstein', 'codigo' => 'LI'],
            ['nome' => 'Lithuania', 'codigo' => 'LT'],
            ['nome' => 'Luxembourg', 'codigo' => 'LU'],
            ['nome' => 'Madagascar', 'codigo' => 'MG'],
            ['nome' => 'Malawi', 'codigo' => 'MW'],
            ['nome' => 'Malaysia', 'codigo' => 'MY'],
            ['nome' => 'Maldives', 'codigo' => 'MV'],
            ['nome' => 'Mali', 'codigo' => 'ML'],
            ['nome' => 'Malta', 'codigo' => 'MT'],
            ['nome' => 'Mauritania', 'codigo' => 'MR'],
            ['nome' => 'Mauritius', 'codigo' => 'MU'],
            ['nome' => 'Mexico', 'codigo' => 'MX'],
            ['nome' => 'Moldova', 'codigo' => 'MD'],
            ['nome' => 'Monaco', 'codigo' => 'MC'],
            ['nome' => 'Mongolia', 'codigo' => 'MN'],
            ['nome' => 'Montenegro', 'codigo' => 'ME'],
            ['nome' => 'Morocco', 'codigo' => 'MA'],
            ['nome' => 'Mozambique', 'codigo' => 'MZ'],
            ['nome' => 'Myanmar', 'codigo' => 'MM'],
            ['nome' => 'Namibia', 'codigo' => 'NA'],
            ['nome' => 'Nepal', 'codigo' => 'NP'],
            ['nome' => 'Netherlands', 'codigo' => 'NL'],
            ['nome' => 'New Zealand', 'codigo' => 'NZ'],
            ['nome' => 'Nicaragua', 'codigo' => 'NI'],
            ['nome' => 'Niger', 'codigo' => 'NE'],
            ['nome' => 'Nigeria', 'codigo' => 'NG'],
            ['nome' => 'North Macedonia', 'codigo' => 'MK'],
            ['nome' => 'Norway', 'codigo' => 'NO'],
            ['nome' => 'Oman', 'codigo' => 'OM'],
            ['nome' => 'Pakistan', 'codigo' => 'PK'],
            ['nome' => 'Palestine', 'codigo' => 'PS'],
            ['nome' => 'Panama', 'codigo' => 'PA'],
            ['nome' => 'Papua New Guinea', 'codigo' => 'PG'],
            ['nome' => 'Paraguay', 'codigo' => 'PY'],
            ['nome' => 'Peru', 'codigo' => 'PE'],
            ['nome' => 'Philippines', 'codigo' => 'PH'],
            ['nome' => 'Poland', 'codigo' => 'PL'],
            ['nome' => 'Portugal', 'codigo' => 'PT'],
            ['nome' => 'Qatar', 'codigo' => 'QA'],
            ['nome' => 'Romania', 'codigo' => 'RO'],
            ['nome' => 'Russia', 'codigo' => 'RU'],
            ['nome' => 'Rwanda', 'codigo' => 'RW'],
            ['nome' => 'Saint Kitts and Nevis', 'codigo' => 'KN'],
            ['nome' => 'Saint Lucia', 'codigo' => 'LC'],
            ['nome' => 'Saint Vincent and the Grenadines', 'codigo' => 'VC'],
            ['nome' => 'Samoa', 'codigo' => 'WS'],
            ['nome' => 'San Marino', 'codigo' => 'SM'],
            ['nome' => 'Saudi Arabia', 'codigo' => 'SA'],
            ['nome' => 'Senegal', 'codigo' => 'SN'],
            ['nome' => 'Serbia', 'codigo' => 'RS'],
            ['nome' => 'Seychelles', 'codigo' => 'SC'],
            ['nome' => 'Sierra Leone', 'codigo' => 'SL'],
            ['nome' => 'Singapore', 'codigo' => 'SG'],
            ['nome' => 'Slovakia', 'codigo' => 'SK'],
            ['nome' => 'Slovenia', 'codigo' => 'SI'],
            ['nome' => 'Somalia', 'codigo' => 'SO'],
            ['nome' => 'South Africa', 'codigo' => 'ZA'],
            ['nome' => 'South Korea', 'codigo' => 'KR'],
            ['nome' => 'Spain', 'codigo' => 'ES'],
            ['nome' => 'Sri Lanka', 'codigo' => 'LK'],
            ['nome' => 'Sudan', 'codigo' => 'SD'],
            ['nome' => 'Suriname', 'codigo' => 'SR'],
            ['nome' => 'Sweden', 'codigo' => 'SE'],
            ['nome' => 'Switzerland', 'codigo' => 'CH'],
            ['nome' => 'Syria', 'codigo' => 'SY'],
            ['nome' => 'Taiwan', 'codigo' => 'TW'],
            ['nome' => 'Tajikistan', 'codigo' => 'TJ'],
            ['nome' => 'Tanzania', 'codigo' => 'TZ'],
            ['nome' => 'Thailand', 'codigo' => 'TH'],
            ['nome' => 'Timor-Leste', 'codigo' => 'TL'],
            ['nome' => 'Togo', 'codigo' => 'TG'],
            ['nome' => 'Trinidad and Tobago', 'codigo' => 'TT'],
            ['nome' => 'Tunisia', 'codigo' => 'TN'],
            ['nome' => 'Turkey', 'codigo' => 'TR'],
            ['nome' => 'Turkmenistan', 'codigo' => 'TM'],
            ['nome' => 'Uganda', 'codigo' => 'UG'],
            ['nome' => 'Ukraine', 'codigo' => 'UA'],
            ['nome' => 'United Arab Emirates', 'codigo' => 'AE'],
            ['nome' => 'United Kingdom', 'codigo' => 'GB'],
            ['nome' => 'United States', 'codigo' => 'US'],
            ['nome' => 'Uruguay', 'codigo' => 'UY'],
            ['nome' => 'Uzbekistan', 'codigo' => 'UZ'],
            ['nome' => 'Venezuela', 'codigo' => 'VE'],
            ['nome' => 'Vietnam', 'codigo' => 'VN'],
            ['nome' => 'Yemen', 'codigo' => 'YE'],
            ['nome' => 'Zambia', 'codigo' => 'ZM'],
            ['nome' => 'Zimbabwe', 'codigo' => 'ZW']
          ];

        foreach ($paises as $pais) {
            Pais::firstOrCreate(
                ['codigo' => $pais['codigo']],
                ['nome' => $pais['nome']]
            );
        }
    }
} 